-- MySQL Script generated by MySQL Workbench
-- Sun May 27 00:21:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ared
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alumno` ;

CREATE USER 'Hector'@'%' IDENTIFIED BY 's13zw98';
GRANT ALL PRIVILEGES ON * . * TO 'Hector'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS `alumno` (
  `idAlumno` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `apellidos` VARCHAR(30) NULL DEFAULT NULL,
  `correoElectronico` VARCHAR(320) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `rutaFoto` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuenta` ;

CREATE TABLE IF NOT EXISTS `cuenta` (
  `usuario` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(64) NULL DEFAULT NULL,
  `tipoCuenta` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo` ;

CREATE TABLE IF NOT EXISTS `grupo` (
  `idGrupo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreGrupo` VARCHAR(100) NULL DEFAULT NULL,
  `usuario` VARCHAR(50) NULL DEFAULT NULL,
  `fechaPago` DATE NULL DEFAULT NULL,
  `estaActivo` INT(11) NULL DEFAULT NULL,
  `mensualidad` DOUBLE NULL DEFAULT NULL,
  `inscripcion` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idGrupo`),
  INDEX `usuario` (`usuario` ASC),
  CONSTRAINT `grupo_ibfk_1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cuenta` (`usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asistencia` ;

CREATE TABLE IF NOT EXISTS `asistencia` (
  `idAsistencia` INT(11) NOT NULL AUTO_INCREMENT,
  `idAlumno` INT(11) NULL DEFAULT NULL,
  `idGrupo` INT(11) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `asistio` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idAsistencia`),
  INDEX `idAlumno` (`idAlumno` ASC),
  INDEX `idGrupo` (`idGrupo` ASC),
  CONSTRAINT `asistencia_ibfk_1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `alumno` (`idAlumno`),
  CONSTRAINT `asistencia_ibfk_2`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `grupo` (`idGrupo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

CREATE TABLE IF NOT EXISTS `cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `apellidos` VARCHAR(30) NULL DEFAULT NULL,
  `correo` VARCHAR(320) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `rutaFoto` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `maestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maestro` ;

CREATE TABLE IF NOT EXISTS `maestro` (
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `apellidos` VARCHAR(30) NULL DEFAULT NULL,
  `correoElectronico` VARCHAR(320) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `estaActivo` INT(11) NULL DEFAULT NULL,
  `fechaCorte` DATE NULL DEFAULT NULL,
  `rutaFoto` VARCHAR(255) NULL DEFAULT NULL,
  `mensualidad` DOUBLE NULL DEFAULT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`usuario`),
  CONSTRAINT `maestro_ibfk_1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cuenta` (`usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `egreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `egreso` ;

CREATE TABLE IF NOT EXISTS `egreso` (
  `idEgreso` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaRegistro` DATE NULL DEFAULT NULL,
  `costo` DOUBLE NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `fechaPublicacion` DATE NULL DEFAULT NULL,
  `fechaFin` DATE NULL DEFAULT NULL,
  `link` VARCHAR(2083) NULL DEFAULT NULL,
  `creador` VARCHAR(50) NULL DEFAULT NULL,
  `nombreGasto` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`idEgreso`),
  INDEX `creador` (`creador` ASC),
  CONSTRAINT `egreso_ibfk_1`
    FOREIGN KEY (`creador`)
    REFERENCES `maestro` (`usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pagoalumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pagoalumno` ;

CREATE TABLE IF NOT EXISTS `pagoalumno` (
  `idPago` INT(11) NOT NULL AUTO_INCREMENT,
  `idAlumno` INT(11) NULL DEFAULT NULL,
  `idGrupo` INT(11) NULL DEFAULT NULL,
  `fechaPago` DATE NULL DEFAULT NULL,
  `cantidad` DOUBLE NULL DEFAULT NULL,
  `tipoPago` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `idAlumno` (`idAlumno` ASC),
  INDEX `idGrupo` (`idGrupo` ASC),
  CONSTRAINT `pagoalumno_ibfk_1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `alumno` (`idAlumno`),
  CONSTRAINT `pagoalumno_ibfk_2`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `grupo` (`idGrupo`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pagoalumnodireccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pagoalumnodireccion` ;

CREATE TABLE IF NOT EXISTS `pagoalumnodireccion` (
  `idPago` INT(11) NOT NULL AUTO_INCREMENT,
  `idAlumno` INT(11) NULL DEFAULT NULL,
  `idGrupo` INT(11) NULL DEFAULT NULL,
  `fechaPago` DATE NULL DEFAULT NULL,
  `cantidad` DOUBLE NULL DEFAULT NULL,
  `usuario` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `idAlumno` (`idAlumno` ASC),
  INDEX `usuario` (`usuario` ASC),
  INDEX `idGrupo` (`idGrupo` ASC),
  CONSTRAINT `pagoalumnodireccion_ibfk_1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `alumno` (`idAlumno`),
  CONSTRAINT `pagoalumnodireccion_ibfk_2`
    FOREIGN KEY (`usuario`)
    REFERENCES `cuenta` (`usuario`),
  CONSTRAINT `pagoalumnodireccion_ibfk_3`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `grupo` (`idGrupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pagomaestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pagomaestro` ;

CREATE TABLE IF NOT EXISTS `pagomaestro` (
  `idPago` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NULL DEFAULT NULL,
  `cantidad` DOUBLE NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pertenece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pertenece` ;

CREATE TABLE IF NOT EXISTS `pertenece` (
  `idAlumno` INT(11) NULL DEFAULT NULL,
  `idGrupo` INT(11) NULL DEFAULT NULL,
  INDEX `idAlumno` (`idAlumno` ASC),
  INDEX `idGrupo` (`idGrupo` ASC),
  CONSTRAINT `pertenece_ibfk_1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `alumno` (`idAlumno`),
  CONSTRAINT `pertenece_ibfk_2`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `grupo` (`idGrupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `promocion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `promocion` ;

CREATE TABLE IF NOT EXISTS `promocion` (
  `idPromocion` INT(11) NOT NULL AUTO_INCREMENT,
  `nombrePromocion` VARCHAR(30) NULL DEFAULT NULL,
  `descripcion` VARCHAR(240) NULL DEFAULT NULL,
  `porcentajeDescuento` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idPromocion`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renta` ;

CREATE TABLE IF NOT EXISTS `renta` (
  `idRenta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreCliente` VARCHAR(65) NULL DEFAULT NULL,
  `Fecha` DATE NULL DEFAULT NULL,
  `Cantidad` DOUBLE NULL DEFAULT NULL,
  `horaInicio` TIME NULL DEFAULT NULL,
  `horaFin` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idRenta`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO CUENTA VALUES('Xavier',sha2('s13zw98',256), "Director");
INSERT INTO MAESTRO VALUES('Xavier','Limón Riaño','hlimon@hotmail.com','2281589647', 0, null, null, null,'Xavier');
